# Generated by Django 4.1.5 on 2023-01-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='department',
        ),
    ]
