# Generated by Django 4.1.6 on 2023-02-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[(' Science', ' Science'), (' Commerce', ' Commerce'), ('Economics', 'Economics'), ('Psycology', 'Psycology'), ('Biochemistry', 'Biochemistry')], max_length=50)),
                ('courses', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Data Scientist', 'Data Scientist'), ('Software Engineer', 'Software Engineer'), ('Physics', 'Physics'), ('Database Management', 'Database Management'), ('Accountant', 'Accountant'), ('Financial Analyst', 'Financial Analyst'), ('Bachelor Of Commerce', 'Bachelor Of Commerce'), ('BBA', 'BBA'), ('Chartered Accountancy', 'Chartered Accountancy'), ('Micro Economics', 'Micro Economics'), ('Macro Economics', 'Macro Economics'), ('Statistics', 'Statistics'), ('Econometrics', 'Econometrics'), ('International Trade', 'International Trade'), ('Modern Applied Psycology', 'Modern Applied Psycology'), ('Forensic Psycology', 'Forensic Psycology'), ('Child Psycology', 'Child Psycology'), ('Environmental Studies', 'Environmental Studies'), ('Biomolecules', 'Biomolecules'), ('Human Physiology', 'Human Physiology')], max_length=50)),
            ],
        ),
    ]
