# Generated by Django 4.1.6 on 2023-02-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='courses',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Data Science', 'Data Science'), ('Software Engineering', 'Software Engineering'), ('Physics', 'Physics'), ('Database Management', 'Database Management'), ('Accountant', 'Accountant'), ('Financial Analyst', 'Financial Analyst'), ('Bachelor Of Commerce', 'Bachelor Of Commerce'), ('BBA', 'BBA'), ('Chartered Accountancy', 'Chartered Accountancy'), ('Micro Economics', 'Micro Economics'), ('Macro Economics', 'Macro Economics'), ('Statistics', 'Statistics'), ('Econometrics', 'Econometrics'), ('International Trade', 'International Trade'), ('Modern Applied Psycology', 'Modern Applied Psycology'), ('Forensic Psycology', 'Forensic Psycology'), ('Child Psycology', 'Child Psycology'), ('Environmental Studies', 'Environmental Studies'), ('Biomolecules', 'Biomolecules'), ('Human Physiology', 'Human Physiology')], max_length=50),
        ),
    ]
